rcc2/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = 'rcc2'
urlpatterns = [
    path('', views.index, name='index'),
    path('shifty/', include('shifty.urls')),
    path('quarks/', include('quarks.urls')),
    path('mobiusutils/', include('mobiusutils.urls')),
    path('admin/', admin.site.urls),
]

shifty/urls.py
from django.urls import path

from . import views

app_name = 'shifty'
urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
    path('add_form', views.add_form, name='add_form'),
    path('add', views.add, name='add'),
    path('<int:mrn>/', views.view_patient, name='view_patient')
]

shifty/models.py
from django.db import models

class TreatmentPosition(models.Model):
    mrn = models.IntegerField()
    date = models.DateField()
    vert = models.DecimalField(max_digits=4, decimal_places=1)
    long = models.DecimalField(max_digits=4, decimal_places=1)
    lat = models.DecimalField(max_digits=4, decimal_places=1)

shifty/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import connections

from rcc2.utils import dictfetchall, crad_to_varian_coords

from .models import TreatmentPosition

def index(request):
    return render(request, 'shifty/index.html')

def list(request):
    with connections['crad'].cursor() as cursor:
        cursor.execute("SELECT * FROM Patient ORDER BY Name")
        patients = dictfetchall(cursor)

    #take out any non-numeric MRNs
    clean_patients = []
    for pt in patients:
        if pt['Patient_ID'].isdigit():
            clean_patients.append(pt)

    return render(request, 'shifty/list.html', {'patients': clean_patients})

def add_form(request):
    return render(request, 'shifty/add_form.html')

def add(request):
    patient_mrn = request.POST['mrn']
    patient_date = request.POST['date']

    try:
        result = TreatmentPosition.objects.filter(mrn__exact=patient_mrn).filter(date__exact=patient_date)[0]
        result.vert = request.POST['vert']
        result.long = request.POST['long']
        result.lat = request.POST['lat']
        result.save()
    except IndexError:
        pos = TreatmentPosition.objects.create(
            mrn = request.POST['mrn'],
            date = request.POST['date'],
            vert = request.POST['vert'],
            long = request.POST['long'],
            lat = request.POST['lat']
        )

    if 'submitagain' in request.POST:
        return render(request, 'shifty/add_form.html', {'mrn': request.POST['mrn']})

    return HttpResponseRedirect(reverse('shifty:index'))

def view_patient(request, mrn):
    with connections['crad'].cursor() as cursor:
        cursor.execute(
            """SELECT PatientSession.PatientSessionID FROM PatientSession
            INNER JOIN Patient ON Patient.PatientID = PatientSession.PatientID
            WHERE Patient.Patient_ID=%s
            ORDER BY PatientSession.CreatedOn DESC""",
            [mrn]
        )
        sessionIDs = cursor.fetchall()
        finalPositions = []
        for sessionID in sessionIDs:
            cursor.execute(
                """SELECT PositionResult.PositionResultID, PositionResult.LiveImageID FROM PositionResult
                INNER JOIN Image ON Image.ImageID = PositionResult.LiveImageID
                WHERE PositionResult.PatientSessionID=%s
                ORDER BY Image.CreatedOn DESC""",
                [sessionID[0]]
            )
            positionResults = cursor.fetchall()
            if positionResults:
                #crad coordinates
                final_pos_sql = "SELECT TOP 1 CreatedOn, CouchVert, CouchLong, CouchLat FROM Image where ImageID='"+positionResults[0][1]+"'"
                for pr in positionResults[1:]:
                    final_pos_sql += " OR ImageID="+"'"+pr[1]+"'"
                final_pos_sql += " ORDER BY CreatedOn DESC"
                cursor.execute(final_pos_sql)
                pos = cursor.fetchone()

                #imaging coordinates
                try:
                    imagingPos = TreatmentPosition.objects.filter(mrn__exact=mrn).filter(date__exact=pos[0])[0]
                    ipos = (imagingPos.vert, imagingPos.long, imagingPos.lat)
                except IndexError:
                    ipos = (None, None, None)

                #original coordinates
                relativeShifts = []
                for pr in positionResults:
                    cursor.execute("SELECT NonRigidPositionResult.TranslationX, NonRigidPositionResult.TranslationY, NonRigidPositionResult.TranslationZ FROM NonRigidPositionResult WHERE NonRigidPositionResult.PositionResultID=%s", [pr[0]])
                    shifts = cursor.fetchone()
                    relativeShifts.append((shifts[0],shifts[1],shifts[2]))
                abs_lat = (-1*relativeShifts[0][0]) + pos[3]
                abs_long = (-1*relativeShifts[0][1]) + pos[2]
                abs_vert = (-1*relativeShifts[0][2]) + pos[1]
                for shift in relativeShifts[1:]:
                    abs_lat -= (-1*shift[0])
                    abs_long -= (-1*shift[1])
                    abs_vert -= (-1*shift[2])

                finalPositions.append({
                    'date': pos[0],
                    'initial': crad_to_varian_coords(abs_vert, abs_long, abs_lat),
                    'crad': crad_to_varian_coords(pos[1], pos[2], pos[3]),
                    'imaging': ipos
                })

        cursor.execute("SELECT Name FROM Patient WHERE Patient_ID=%s",[mrn])
        name = cursor.fetchone()

    return render(request, 'shifty/view_patient.html', {'name':name[0], 'mrn':mrn, 'finalPositions':finalPositions})

shifty/templates/shifty/add_form.html
{% extends 'base.html' %}

{% block content %}

<h1>Add Final Treatment Position</h1>

<form action="{% url 'shifty:add' %}" method="post">
{% csrf_token %}
  <div class="row">
    <div class="col-1 text-right">
      <label for="mrn">MRN</label>
    </div>
    <div class="col">
      <input type="text" name="mrn" id="mrn" value="{{ mrn }}"/><br />
    </div>
  </div>
  <div class="row">
    <div class="col-1 text-right">
      <label for="date">Date</label>
    </div>
    <div class="col">
      <input type="date" name="date" id="date" /><br />
    </div>
  </div>
  <div class="row">
    <div class="col-1 text-right">
      <label for="vert">Vert</label>
    </div>
    <div class="col">
      <input type="text" name="vert" id="vert" /><br />
    </div>
  </div>
  <div class="row">
    <div class="col-1 text-right">
      <label for="long">Long</label>
    </div>
    <div class="col">
      <input type="text" name="long" id="long" /><br />
    </div>
  </div>
  <div class="row">
    <div class="col-1 text-right">
      <label for="lat">Lat</label>
    </div>
    <div class="col">
      <input type="text" name="lat" id="lat" /><br />
    </div>
  </div>
  <br />
  <input type="submit" class="btn btn-primary" value="Submit" name="submit" />
  <input type="submit" class="btn btn-outline-primary" value="Submit and Enter Another" name="submitagain" />
</form>

{% endblock %}

shifty/templates/shifty/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load bootstrap4 %}

    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}

    {% bootstrap_messages %}
  </head>

  <body>
    {% block content %}
    {% endblock %}

    <br /><br />
    <a href="{% url 'shifty:index' %}">Home</a>
  </body>
</html>

shifty/templates/shifty/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Shifty</h1>

<a href="{% url 'shifty:add_form' %}">Add a Position</a>
<br />
<a href="{% url 'shifty:list' %}">List all Patients</a>

{% endblock %}

shifty/templates/shifty/list.html
{% extends 'base.html' %}

{% block content %}

<h1>All Patients:</h1>
<ul>
    {% for patient in patients %}
    <li><a href="{% url 'shifty:view_patient' patient.Patient_ID %}">{{ patient.Patient_ID }}</a> - {{ patient.Name }}</li>
    {% endfor %}
</ul>

{% endblock %}

shifty/templates/shifty/view_patient.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ name }} -- {{ mrn }}</h1>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Date</th>
      <th></th>
      <th>Initial</th>
      <th>C-RAD</th>
      <th>Imaging</th>
    </tr>
  </thead>
  <tbody>
    {% for fp in finalPositions %}
    <tr>
      <td class="align-middle">{{ fp.date|date:"SHORT_DATE_FORMAT" }}</td>
      <td>
        <div>
          Vert<br />
          Long<br />
          Lat
        </div>
      </td>
      <td>
        <div>
          {{ fp.initial.0 }}<br />
          {{ fp.initial.1 }}<br />
          {{ fp.initial.2 }}
        </div>
      </td>
      <td>
        <div>
          {{ fp.crad.0 }}<br />
          {{ fp.crad.1 }}<br />
          {{ fp.crad.2 }}
        </div>
      </td>
      <td>
        <div>
          {{ fp.imaging.0 }}<br />
          {{ fp.imaging.1 }}<br />
          {{ fp.imaging.2 }}
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}