mobiusutils/urls.py
from django.urls import path

from . import views

app_name = 'mobiusutils'
urlpatterns = [
    path('list/', views.list, name='list'),
]

rcc2/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = 'rcc2'
urlpatterns = [
    path('', views.index, name='index'),
    path('shifty/', include('shifty.urls')),
    path('quarks/', include('quarks.urls')),
    path('mobiusutils/', include('mobiusutils.urls')),
    path('admin/', admin.site.urls),
]

shifty/urls.py
from django.urls import path

from . import views

app_name = 'shifty'
urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
    path('add_form', views.add_form, name='add_form'),
    path('add', views.add, name='add'),
    path('<int:mrn>/', views.view_patient, name='view_patient')
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load bootstrap4 %}

    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}

    {% bootstrap_messages %}

    <title>RCC2</title>
  </head>

  <body>
    <div class="container-fluid">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <h2>C-RAD Tools</h2>
    <ul>
      <li><a href="{% url 'shifty:index' %}">Shifty</a></li>
    </ul>
    <h2>Mobius Tools</h2>
    <ul>
      <li><a href="{% url 'mobiusutils:list' %}">Email Notification</a></li>
    </ul>
{% endblock %}